export type EmojiOption = {
  emoji: string
  labelKey: string
}

type EmojiDefinition = {
  emoji: string
  key: string
  pt: string
  en: string
  es: string
  de: string
}

const EMOJI_DEFINITIONS: EmojiDefinition[] = [
  { emoji: '🏃', key: 'run', pt: 'Corrida', en: 'Run', es: 'Carrera', de: 'Lauf' },
  { emoji: '🏃‍♀️', key: 'run_woman', pt: 'Corrida (mulher)', en: 'Run (woman)', es: 'Carrera (mujer)', de: 'Lauf (Frau)' },
  { emoji: '🏃‍♂️', key: 'run_man', pt: 'Corrida (homem)', en: 'Run (man)', es: 'Carrera (hombre)', de: 'Lauf (Mann)' },
  { emoji: '🏆', key: 'trophy', pt: 'Troféu', en: 'Trophy', es: 'Trofeo', de: 'Trophäe' },
  { emoji: '🥇', key: 'gold', pt: 'Ouro', en: 'Gold', es: 'Oro', de: 'Gold' },
  { emoji: '🥈', key: 'silver', pt: 'Prata', en: 'Silver', es: 'Plata', de: 'Silber' },
  { emoji: '🥉', key: 'bronze', pt: 'Bronze', en: 'Bronze', es: 'Bronce', de: 'Bronze' },
  { emoji: '🏅', key: 'medal', pt: 'Medalha', en: 'Medal', es: 'Medalla', de: 'Medaille' },
  { emoji: '🎖️', key: 'decoration', pt: 'Condecoração', en: 'Decoration', es: 'Condecoración', de: 'Auszeichnung' },
  { emoji: '🌳', key: 'tree_park', pt: 'Árvore / parque', en: 'Tree / park', es: 'Árbol / parque', de: 'Baum / Park' },
  { emoji: '🌲', key: 'pine_forest', pt: 'Pinheiro / floresta', en: 'Pine / forest', es: 'Pino / bosque', de: 'Kiefer / Wald' },
  { emoji: '🏞️', key: 'natural_landscape', pt: 'Paisagem natural', en: 'Natural landscape', es: 'Paisaje natural', de: 'Naturlandschaft' },
  { emoji: '🏙️', key: 'city', pt: 'Cidade', en: 'City', es: 'Ciudad', de: 'Stadt' },
  { emoji: '🌆', key: 'city_sunset', pt: 'Cidade ao entardecer', en: 'City at dusk', es: 'Ciudad al atardecer', de: 'Stadt in der Dämmerung' },
  { emoji: '🌉', key: 'bridge', pt: 'Ponte', en: 'Bridge', es: 'Puente', de: 'Brücke' },
  { emoji: '🗼', key: 'monument_tower', pt: 'Monumento / torre', en: 'Monument / tower', es: 'Monumento / torre', de: 'Denkmal / Turm' },
  { emoji: '🏔️', key: 'mountain_snow', pt: 'Montanha com neve', en: 'Snow-capped mountain', es: 'Montaña nevada', de: 'Schneebedeckter Berg' },
  { emoji: '⛰️', key: 'mountain', pt: 'Montanha', en: 'Mountain', es: 'Montaña', de: 'Berg' },
  { emoji: '🌊', key: 'sea_waves', pt: 'Mar / ondas', en: 'Sea / waves', es: 'Mar / olas', de: 'Meer / Wellen' },
  { emoji: '🏖️', key: 'beach', pt: 'Praia', en: 'Beach', es: 'Playa', de: 'Strand' },
  { emoji: '🏟️', key: 'stadium', pt: 'Estádio', en: 'Stadium', es: 'Estadio', de: 'Stadion' },
  { emoji: '🛣️', key: 'road_highway', pt: 'Estrada / autoestrada', en: 'Road / motorway', es: 'Carretera / autopista', de: 'Straße / Autobahn' },
  { emoji: '🛤️', key: 'trail_path', pt: 'Trilho / caminho', en: 'Trail / path', es: 'Sendero / camino', de: 'Pfad / Weg' },
  { emoji: '🏁', key: 'finish_circuit', pt: 'Meta / circuito', en: 'Finish / circuit', es: 'Meta / circuito', de: 'Ziel / Runde' },
  { emoji: '🏜️', key: 'desert', pt: 'Deserto', en: 'Desert', es: 'Desierto', de: 'Wüste' },
  { emoji: '🏝️', key: 'island', pt: 'Ilha', en: 'Island', es: 'Isla', de: 'Insel' },
  { emoji: '🌴', key: 'tropical_island', pt: 'Ilha tropical', en: 'Tropical island', es: 'Isla tropical', de: 'Tropeninsel' },
  { emoji: '🏕️', key: 'camping', pt: 'Campismo', en: 'Camping', es: 'Camping', de: 'Camping' },
  { emoji: '⛺', key: 'tent_outdoors', pt: 'Tenda / ar livre', en: 'Tent / outdoors', es: 'Tienda / al aire libre', de: 'Zelt / draußen' },
  { emoji: '🏘️', key: 'village', pt: 'Bairro / aldeia', en: 'Neighbourhood / village', es: 'Barrio / pueblo', de: 'Viertel / Dorf' },
  { emoji: '🏛️', key: 'classical_monument', pt: 'Monumento clássico', en: 'Classical monument', es: 'Monumento clásico', de: 'Klassisches Denkmal' },
  { emoji: '🏰', key: 'castle', pt: 'Castelo', en: 'Castle', es: 'Castillo', de: 'Schloss' },
  { emoji: '🌁', key: 'foggy_city', pt: 'Cidade com nevoeiro', en: 'Foggy city', es: 'Ciudad con niebla', de: 'Neblige Stadt' },
  { emoji: '🗻', key: 'snowy_mountain', pt: 'Montanha nevada', en: 'Snowy mountain', es: 'Montaña nevada', de: 'Verschneiter Berg' },
  { emoji: '🌋', key: 'volcano', pt: 'Vulcão', en: 'Volcano', es: 'Volcán', de: 'Vulkan' },
  { emoji: '🪨', key: 'rock_terrain', pt: 'Rocha / terreno', en: 'Rock / terrain', es: 'Roca / terreno', de: 'Fels / Gelände' },
  { emoji: '🌾', key: 'open_field', pt: 'Campo aberto', en: 'Open field', es: 'Campo abierto', de: 'Offenes Feld' },
  { emoji: '🚇', key: 'metro_urban', pt: 'Metro / urbano', en: 'Metro / urban', es: 'Metro / urbano', de: 'U-Bahn / urban' },
  { emoji: '✈️', key: 'airplane', pt: 'Avião', en: 'Airplane', es: 'Avión', de: 'Flugzeug' },
  { emoji: '🛫', key: 'airplane_departure', pt: 'Avião a descolar / aeroporto', en: 'Airplane departure / airport', es: 'Salida de avión / aeropuerto', de: 'Flugzeug startet / Flughafen' },
  { emoji: '🛬', key: 'airplane_arrival', pt: 'Avião a aterrar / aeroporto', en: 'Airplane arrival / airport', es: 'Llegada de avión / aeropuerto', de: 'Flugzeug landet / Flughafen' },
  { emoji: '🛩️', key: 'small_airplane', pt: 'Avião pequeno', en: 'Small airplane', es: 'Avión pequeño', de: 'Kleines Flugzeug' },
  { emoji: '🛄', key: 'baggage_airport', pt: 'Bagagem / aeroporto', en: 'Baggage / airport', es: 'Equipaje / aeropuerto', de: 'Gepäck / Flughafen' },
  { emoji: '🧳', key: 'luggage_travel', pt: 'Mala / viagem', en: 'Luggage / travel', es: 'Maleta / viaje', de: 'Koffer / Reise' },
  { emoji: '🚂', key: 'train_locomotive', pt: 'Comboio (locomotiva)', en: 'Train (locomotive)', es: 'Tren (locomotora)', de: 'Zug (Lokomotive)' },
  { emoji: '🚆', key: 'train', pt: 'Comboio', en: 'Train', es: 'Tren', de: 'Zug' },
  { emoji: '🚄', key: 'high_speed_train', pt: 'Comboio de alta velocidade', en: 'High-speed train', es: 'Tren de alta velocidad', de: 'Hochgeschwindigkeitszug' },
  { emoji: '🚅', key: 'bullet_train', pt: 'Comboio bala', en: 'Bullet train', es: 'Tren bala', de: 'Schnellzug' },
  { emoji: '🚉', key: 'train_station', pt: 'Estação de comboio', en: 'Train station', es: 'Estación de tren', de: 'Bahnhof' },
  { emoji: '🛳️', key: 'ship_coast', pt: 'Navio / costa', en: 'Ship / coast', es: 'Barco / costa', de: 'Schiff / Küste' },
  { emoji: '⚓', key: 'port_anchor', pt: 'Porto / âncora', en: 'Port / anchor', es: 'Puerto / ancla', de: 'Hafen / Anker' },
  { emoji: '☀️', key: 'sun_summer', pt: 'Sol / verão', en: 'Sun / summer', es: 'Sol / verano', de: 'Sonne / Sommer' },
  { emoji: '🌤️', key: 'sun_clouds', pt: 'Sol com nuvens', en: 'Sun with clouds', es: 'Sol con nubes', de: 'Sonne mit Wolken' },
  { emoji: '🌧️', key: 'rain', pt: 'Chuva', en: 'Rain', es: 'Lluvia', de: 'Regen' },
  { emoji: '❄️', key: 'snow_winter', pt: 'Neve / inverno', en: 'Snow / winter', es: 'Nieve / invierno', de: 'Schnee / Winter' },
  { emoji: '🌙', key: 'crescent_moon', pt: 'Lua crescente', en: 'Crescent moon', es: 'Luna creciente', de: 'Zunehmender Mond' },
  { emoji: '🌕', key: 'full_moon', pt: 'Lua cheia', en: 'Full moon', es: 'Luna llena', de: 'Vollmond' },
  { emoji: '🌑', key: 'new_moon', pt: 'Lua nova', en: 'New moon', es: 'Luna nueva', de: 'Neumond' },
  { emoji: '🌛', key: 'first_quarter_moon', pt: 'Lua (quarto crescente)', en: 'First quarter moon', es: 'Cuarto creciente', de: 'Erstes Viertel' },
  { emoji: '🌜', key: 'last_quarter_moon', pt: 'Lua (quarto minguante)', en: 'Last quarter moon', es: 'Cuarto menguante', de: 'Letztes Viertel' },
  { emoji: '🌃', key: 'night_stars', pt: 'Noite com estrelas', en: 'Night with stars', es: 'Noche con estrellas', de: 'Nacht mit Sternen' },
  { emoji: '🌌', key: 'milky_way', pt: 'Via Láctea / noite', en: 'Milky Way / night sky', es: 'Vía Láctea / cielo nocturno', de: 'Milchstraße / Nachthimmel' },
  { emoji: '🌠', key: 'shooting_star_night', pt: 'Estrela cadente / noite', en: 'Shooting star / night', es: 'Estrella fugaz / noche', de: 'Sternschnuppe / Nacht' },
  { emoji: '🌟', key: 'star_bright', pt: 'Estrela brilhante', en: 'Glowing star', es: 'Estrella brillante', de: 'Leuchtender Stern' },
  { emoji: '⭐', key: 'star', pt: 'Estrela', en: 'Star', es: 'Estrella', de: 'Stern' },
  { emoji: '✨', key: 'sparkle', pt: 'Brilho', en: 'Sparkle', es: 'Destellos', de: 'Funkeln' },
  { emoji: '💫', key: 'shooting_star', pt: 'Estrela cadente', en: 'Shooting star', es: 'Estrella fugaz', de: 'Sternschnuppe' },
  { emoji: '🔥', key: 'fire_intensity', pt: 'Fogo / intensidade', en: 'Fire / intensity', es: 'Fuego / intensidad', de: 'Feuer / Intensität' },
  { emoji: '💨', key: 'speed', pt: 'Velocidade', en: 'Speed', es: 'Velocidad', de: 'Geschwindigkeit' },
  { emoji: '⚡', key: 'energy', pt: 'Energia', en: 'Energy', es: 'Energía', de: 'Energie' },
  { emoji: '💪', key: 'strength', pt: 'Força', en: 'Strength', es: 'Fuerza', de: 'Kraft' },
  { emoji: '🎯', key: 'goal', pt: 'Objetivo', en: 'Goal', es: 'Objetivo', de: 'Ziel' },
  { emoji: '🚀', key: 'rocket_record', pt: 'Foguete / recorde', en: 'Rocket / record', es: 'Cohete / récord', de: 'Rakete / Rekord' },
  { emoji: '🦅', key: 'eagle', pt: 'Águia', en: 'Eagle', es: 'Águila', de: 'Adler' },
  { emoji: '🐢', key: 'turtle_slow_pace', pt: 'Tartaruga / ritmo lento', en: 'Turtle / slow pace', es: 'Tortuga / ritmo lento', de: 'Schildkröte / langsames Tempo' },
  { emoji: '🐇', key: 'rabbit_fast_pace', pt: 'Coelho / ritmo rápido', en: 'Rabbit / fast pace', es: 'Conejo / ritmo rápido', de: 'Hase / schnelles Tempo' },
  { emoji: '🦌', key: 'deer', pt: 'Veado', en: 'Deer', es: 'Ciervo', de: 'Hirsch' },
  { emoji: '🐕', key: 'dog', pt: 'Cão', en: 'Dog', es: 'Perro', de: 'Hund' },
  { emoji: '🦁', key: 'lion', pt: 'Leão', en: 'Lion', es: 'León', de: 'Löwe' },
  { emoji: '🦙', key: 'llama', pt: 'Lhama', en: 'Llama', es: 'Llama', de: 'Lama' },
  { emoji: '🦏', key: 'rhino', pt: 'Rinoceronte', en: 'Rhinoceros', es: 'Rinoceronte', de: 'Nashorn' },
  { emoji: '🐨', key: 'koala', pt: 'Coala', en: 'Koala', es: 'Koala', de: 'Koala' },
  { emoji: '🐒', key: 'monkey', pt: 'Macaco', en: 'Monkey', es: 'Mono', de: 'Affe' },
  { emoji: '🐷', key: 'pig', pt: 'Porco', en: 'Pig', es: 'Cerdo', de: 'Schwein' },
  { emoji: '🐄', key: 'cow', pt: 'Vaca', en: 'Cow', es: 'Vaca', de: 'Kuh' },
  { emoji: '🦆', key: 'duck', pt: 'Pato', en: 'Duck', es: 'Pato', de: 'Ente' },
  { emoji: '🐀', key: 'rat', pt: 'Rato', en: 'Rat', es: 'Rata', de: 'Ratte' },
  { emoji: '🫎', key: 'moose', pt: 'Alce', en: 'Moose', es: 'Alce', de: 'Elch' },
  { emoji: '🐟', key: 'fish', pt: 'Peixe', en: 'Fish', es: 'Pez', de: 'Fisch' },
  { emoji: '🎉', key: 'celebration', pt: 'Celebração', en: 'Celebration', es: 'Celebración', de: 'Feier' },
  { emoji: '🎊', key: 'confetti', pt: 'Confetti', en: 'Confetti', es: 'Confeti', de: 'Konfetti' },
  { emoji: '🎅', key: 'santa_nikolaus', pt: 'Pai Natal / Nikolaus', en: 'Santa / Nikolaus', es: 'Papá Noel / Nikolaus', de: 'Weihnachtsmann / Nikolaus' },
  { emoji: '🤶', key: 'mrs_santa', pt: 'Mãe Natal', en: 'Mrs Claus', es: 'Mamá Noel', de: 'Frau Weihnachtsmann' },
  { emoji: '🧑‍🎄', key: 'santa_alt', pt: 'Pai Natal (alternativo)', en: 'Santa (alternate)', es: 'Papá Noel (alternativo)', de: 'Weihnachtsmann (alternativ)' },
  { emoji: '🎄', key: 'christmas_tree', pt: 'Árvore de Natal', en: 'Christmas tree', es: 'Árbol de Navidad', de: 'Weihnachtsbaum' },
  { emoji: '🎁', key: 'gift', pt: 'Prenda', en: 'Gift', es: 'Regalo', de: 'Geschenk' },
  { emoji: '🕯️', key: 'candle_advent', pt: 'Vela / Advento', en: 'Candle / Advent', es: 'Vela / Adviento', de: 'Kerze / Advent' },
  { emoji: '⛄', key: 'snowman', pt: 'Boneco de neve', en: 'Snowman', es: 'Muñeco de nieve', de: 'Schneemann' },
  { emoji: '🎂', key: 'birthday', pt: 'Aniversário', en: 'Birthday', es: 'Cumpleaños', de: 'Geburtstag' },
  { emoji: '🥳', key: 'party', pt: 'Festa', en: 'Party', es: 'Fiesta', de: 'Party' },
  { emoji: '🎈', key: 'balloons', pt: 'Balões', en: 'Balloons', es: 'Globos', de: 'Luftballons' },
  { emoji: '🎀', key: 'ribbon_gift', pt: 'Laço / oferta', en: 'Ribbon / gift', es: 'Lazo / regalo', de: 'Schleife / Geschenk' },
  { emoji: '🎆', key: 'fireworks', pt: 'Fogo de artifício', en: 'Fireworks', es: 'Fuegos artificiales', de: 'Feuerwerk' },
  { emoji: '🎇', key: 'sparks', pt: 'Faíscas', en: 'Sparks', es: 'Chispas', de: 'Funken' },
  { emoji: '🥂', key: 'toast', pt: 'Brinde', en: 'Toast', es: 'Brindis', de: 'Prosit' },
  { emoji: '🍾', key: 'champagne', pt: 'Champanhe', en: 'Champagne', es: 'Champán', de: 'Champagner' },
  { emoji: '🎃', key: 'halloween', pt: 'Halloween', en: 'Halloween', es: 'Halloween', de: 'Halloween' },
  { emoji: '🪅', key: 'pinata', pt: 'Pinhata', en: 'Piñata', es: 'Piñata', de: 'Piñata' },
  { emoji: '🎭', key: 'carnival_mask', pt: 'Carnaval / máscara', en: 'Carnival / mask', es: 'Carnaval / máscara', de: 'Karneval / Maske' },
  { emoji: '🪩', key: 'disco_party', pt: 'Disco / festa', en: 'Disco / party', es: 'Disco / fiesta', de: 'Disco / Party' },
  { emoji: '🍀', key: 'clover_luck', pt: 'Trevo / sorte', en: 'Clover / luck', es: 'Trébol / suerte', de: 'Klee / Glück' },
  { emoji: '❤️', key: 'heart_red', pt: 'Coração vermelho', en: 'Red heart', es: 'Corazón rojo', de: 'Rotes Herz' },
  { emoji: '💙', key: 'heart_blue', pt: 'Coração azul', en: 'Blue heart', es: 'Corazón azul', de: 'Blaues Herz' },
  { emoji: '💚', key: 'heart_green', pt: 'Coração verde', en: 'Green heart', es: 'Corazón verde', de: 'Grünes Herz' },
  { emoji: '🧡', key: 'heart_orange', pt: 'Coração laranja', en: 'Orange heart', es: 'Corazón naranja', de: 'Oranges Herz' },
  { emoji: '💜', key: 'heart_purple', pt: 'Coração roxo', en: 'Purple heart', es: 'Corazón morado', de: 'Violettes Herz' },
  { emoji: '🖤', key: 'heart_black', pt: 'Coração preto', en: 'Black heart', es: 'Corazón negro', de: 'Schwarzes Herz' },
  { emoji: '🤍', key: 'heart_white', pt: 'Coração branco', en: 'White heart', es: 'Corazón blanco', de: 'Weißes Herz' },
  { emoji: '🇦🇱', key: 'country_al', pt: 'Albânia', en: 'Albania', es: 'Albania', de: 'Albanien' },
  { emoji: '🇦🇩', key: 'country_ad', pt: 'Andorra', en: 'Andorra', es: 'Andorra', de: 'Andorra' },
  { emoji: '🇦🇲', key: 'country_am', pt: 'Arménia', en: 'Armenia', es: 'Armenia', de: 'Armenien' },
  { emoji: '🇦🇹', key: 'country_at', pt: 'Áustria', en: 'Austria', es: 'Austria', de: 'Österreich' },
  { emoji: '🇦🇿', key: 'country_az', pt: 'Azerbaijão', en: 'Azerbaijan', es: 'Azerbaiyán', de: 'Aserbaidschan' },
  { emoji: '🇧🇾', key: 'country_by', pt: 'Bielorrússia', en: 'Belarus', es: 'Bielorrusia', de: 'Belarus' },
  { emoji: '🇧🇪', key: 'country_be', pt: 'Bélgica', en: 'Belgium', es: 'Bélgica', de: 'Belgien' },
  { emoji: '🇧🇦', key: 'country_ba', pt: 'Bósnia e Herzegovina', en: 'Bosnia and Herzegovina', es: 'Bosnia y Herzegovina', de: 'Bosnien und Herzegowina' },
  { emoji: '🇧🇬', key: 'country_bg', pt: 'Bulgária', en: 'Bulgaria', es: 'Bulgaria', de: 'Bulgarien' },
  { emoji: '🇭🇷', key: 'country_hr', pt: 'Croácia', en: 'Croatia', es: 'Croacia', de: 'Kroatien' },
  { emoji: '🇨🇾', key: 'country_cy', pt: 'Chipre', en: 'Cyprus', es: 'Chipre', de: 'Zypern' },
  { emoji: '🇨🇿', key: 'country_cz', pt: 'Chéquia', en: 'Czechia', es: 'Chequia', de: 'Tschechien' },
  { emoji: '🇩🇰', key: 'country_dk', pt: 'Dinamarca', en: 'Denmark', es: 'Dinamarca', de: 'Dänemark' },
  { emoji: '🇪🇬', key: 'country_eg', pt: 'Egito', en: 'Egypt', es: 'Egipto', de: 'Ägypten' },
  { emoji: '🇪🇪', key: 'country_ee', pt: 'Estónia', en: 'Estonia', es: 'Estonia', de: 'Estland' },
  { emoji: '🇫🇮', key: 'country_fi', pt: 'Finlândia', en: 'Finland', es: 'Finlandia', de: 'Finnland' },
  { emoji: '🇫🇷', key: 'country_fr', pt: 'França', en: 'France', es: 'Francia', de: 'Frankreich' },
  { emoji: '🇬🇪', key: 'country_ge', pt: 'Geórgia', en: 'Georgia', es: 'Georgia', de: 'Georgien' },
  { emoji: '🇩🇪', key: 'country_de', pt: 'Alemanha', en: 'Germany', es: 'Alemania', de: 'Deutschland' },
  { emoji: '🇬🇷', key: 'country_gr', pt: 'Grécia', en: 'Greece', es: 'Grecia', de: 'Griechenland' },
  { emoji: '🇭🇺', key: 'country_hu', pt: 'Hungria', en: 'Hungary', es: 'Hungría', de: 'Ungarn' },
  { emoji: '🇮🇸', key: 'country_is', pt: 'Islândia', en: 'Iceland', es: 'Islandia', de: 'Island' },
  { emoji: '🇮🇪', key: 'country_ie', pt: 'Irlanda', en: 'Ireland', es: 'Irlanda', de: 'Irland' },
  { emoji: '🇮🇹', key: 'country_it', pt: 'Itália', en: 'Italy', es: 'Italia', de: 'Italien' },
  { emoji: '🇱🇻', key: 'country_lv', pt: 'Letónia', en: 'Latvia', es: 'Letonia', de: 'Lettland' },
  { emoji: '🇱🇹', key: 'country_lt', pt: 'Lituânia', en: 'Lithuania', es: 'Lituania', de: 'Litauen' },
  { emoji: '🇱🇺', key: 'country_lu', pt: 'Luxemburgo', en: 'Luxembourg', es: 'Luxemburgo', de: 'Luxemburg' },
  { emoji: '🇲🇦', key: 'country_ma', pt: 'Marrocos', en: 'Morocco', es: 'Marruecos', de: 'Marokko' },
  { emoji: '🇲🇩', key: 'country_md', pt: 'Moldávia', en: 'Moldova', es: 'Moldavia', de: 'Moldawien' },
  { emoji: '🇲🇨', key: 'country_mc', pt: 'Mónaco', en: 'Monaco', es: 'Mónaco', de: 'Monaco' },
  { emoji: '🇳🇱', key: 'country_nl', pt: 'Países Baixos', en: 'Netherlands', es: 'Países Bajos', de: 'Niederlande' },
  { emoji: '🇳🇴', key: 'country_no', pt: 'Noruega', en: 'Norway', es: 'Noruega', de: 'Norwegen' },
  { emoji: '🇵🇱', key: 'country_pl', pt: 'Polónia', en: 'Poland', es: 'Polonia', de: 'Polen' },
  { emoji: '🇵🇹', key: 'country_pt', pt: 'Portugal', en: 'Portugal', es: 'Portugal', de: 'Portugal' },
  { emoji: '🇷🇴', key: 'country_ro', pt: 'Roménia', en: 'Romania', es: 'Rumanía', de: 'Rumänien' },
  { emoji: '🇷🇺', key: 'country_ru', pt: 'Rússia', en: 'Russia', es: 'Rusia', de: 'Russland' },
  { emoji: '🇷🇸', key: 'country_rs', pt: 'Sérvia', en: 'Serbia', es: 'Serbia', de: 'Serbien' },
  { emoji: '🇸🇰', key: 'country_sk', pt: 'Eslováquia', en: 'Slovakia', es: 'Eslovaquia', de: 'Slowakei' },
  { emoji: '🇸🇮', key: 'country_si', pt: 'Eslovénia', en: 'Slovenia', es: 'Eslovenia', de: 'Slowenien' },
  { emoji: '🇪🇸', key: 'country_es', pt: 'Espanha', en: 'Spain', es: 'España', de: 'Spanien' },
  { emoji: '🇸🇪', key: 'country_se', pt: 'Suécia', en: 'Sweden', es: 'Suecia', de: 'Schweden' },
  { emoji: '🇨🇭', key: 'country_ch', pt: 'Suíça', en: 'Switzerland', es: 'Suiza', de: 'Schweiz' },
  { emoji: '🇹🇷', key: 'country_tr', pt: 'Turquia', en: 'Turkey', es: 'Turquía', de: 'Türkei' },
  { emoji: '🇺🇦', key: 'country_ua', pt: 'Ucrânia', en: 'Ukraine', es: 'Ucrania', de: 'Ukraine' },
  { emoji: '🇬🇧', key: 'country_gb', pt: 'Reino Unido', en: 'United Kingdom', es: 'Reino Unido', de: 'Vereinigtes Königreich' },
  { emoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', key: 'country_scotland', pt: 'Escócia', en: 'Scotland', es: 'Escocia', de: 'Schottland' },
  { emoji: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', key: 'country_wales', pt: 'País de Gales', en: 'Wales', es: 'Gales', de: 'Wales' },
  { emoji: '🏴󠁧󠁢󠁮󠁩󠁲󠁿', key: 'country_northern_ireland', pt: 'Irlanda do Norte', en: 'Northern Ireland', es: 'Irlanda del Norte', de: 'Nordirland' },
]

export const EMOJI_OPTIONS: EmojiOption[] = EMOJI_DEFINITIONS.map(({ emoji, key }) => ({
  emoji,
  labelKey: key,
}))

export function buildEmojiLocaleResources(): {
  pt: Record<string, string>
  en: Record<string, string>
  es: Record<string, string>
  de: Record<string, string>
} {
  const pt: Record<string, string> = {}
  const en: Record<string, string> = {}
  const es: Record<string, string> = {}
  const de: Record<string, string> = {}

  for (const { key, pt: ptLabel, en: enLabel, es: esLabel, de: deLabel } of EMOJI_DEFINITIONS) {
    pt[key] = ptLabel
    en[key] = enLabel
    es[key] = esLabel
    de[key] = deLabel
  }

  return { pt, en, es, de }
}
