export type EmojiOption = {
  emoji: string
  labelKey: string
}

type EmojiDefinition = {
  emoji: string
  key: string
  pt: string
  en: string
}

const EMOJI_DEFINITIONS: EmojiDefinition[] = [
  { emoji: '🏃', key: 'run', pt: 'Corrida', en: 'Run' },
  { emoji: '🏃‍♀️', key: 'run_woman', pt: 'Corrida (mulher)', en: 'Run (woman)' },
  { emoji: '🏃‍♂️', key: 'run_man', pt: 'Corrida (homem)', en: 'Run (man)' },
  { emoji: '🏆', key: 'trophy', pt: 'Troféu', en: 'Trophy' },
  { emoji: '🥇', key: 'gold', pt: 'Ouro', en: 'Gold' },
  { emoji: '🥈', key: 'silver', pt: 'Prata', en: 'Silver' },
  { emoji: '🥉', key: 'bronze', pt: 'Bronze', en: 'Bronze' },
  { emoji: '🏅', key: 'medal', pt: 'Medalha', en: 'Medal' },
  { emoji: '🎖️', key: 'decoration', pt: 'Condecoração', en: 'Decoration' },
  { emoji: '🌳', key: 'tree_park', pt: 'Árvore / parque', en: 'Tree / park' },
  { emoji: '🌲', key: 'pine_forest', pt: 'Pinheiro / floresta', en: 'Pine / forest' },
  { emoji: '🏞️', key: 'natural_landscape', pt: 'Paisagem natural', en: 'Natural landscape' },
  { emoji: '🏙️', key: 'city', pt: 'Cidade', en: 'City' },
  { emoji: '🌆', key: 'city_sunset', pt: 'Cidade ao entardecer', en: 'City at dusk' },
  { emoji: '🌉', key: 'bridge', pt: 'Ponte', en: 'Bridge' },
  { emoji: '🗼', key: 'monument_tower', pt: 'Monumento / torre', en: 'Monument / tower' },
  { emoji: '🏔️', key: 'mountain_snow', pt: 'Montanha com neve', en: 'Snow-capped mountain' },
  { emoji: '⛰️', key: 'mountain', pt: 'Montanha', en: 'Mountain' },
  { emoji: '🌊', key: 'sea_waves', pt: 'Mar / ondas', en: 'Sea / waves' },
  { emoji: '🏖️', key: 'beach', pt: 'Praia', en: 'Beach' },
  { emoji: '🏟️', key: 'stadium', pt: 'Estádio', en: 'Stadium' },
  { emoji: '🛣️', key: 'road_highway', pt: 'Estrada / autoestrada', en: 'Road / motorway' },
  { emoji: '🛤️', key: 'trail_path', pt: 'Trilho / caminho', en: 'Trail / path' },
  { emoji: '🏁', key: 'finish_circuit', pt: 'Meta / circuito', en: 'Finish / circuit' },
  { emoji: '🏜️', key: 'desert', pt: 'Deserto', en: 'Desert' },
  { emoji: '🏝️', key: 'island', pt: 'Ilha', en: 'Island' },
  { emoji: '🌴', key: 'tropical_island', pt: 'Ilha tropical', en: 'Tropical island' },
  { emoji: '🏕️', key: 'camping', pt: 'Campismo', en: 'Camping' },
  { emoji: '⛺', key: 'tent_outdoors', pt: 'Tenda / ar livre', en: 'Tent / outdoors' },
  { emoji: '🏘️', key: 'village', pt: 'Bairro / aldeia', en: 'Neighbourhood / village' },
  { emoji: '🏛️', key: 'classical_monument', pt: 'Monumento clássico', en: 'Classical monument' },
  { emoji: '🏰', key: 'castle', pt: 'Castelo', en: 'Castle' },
  { emoji: '🌁', key: 'foggy_city', pt: 'Cidade com nevoeiro', en: 'Foggy city' },
  { emoji: '🗻', key: 'snowy_mountain', pt: 'Montanha nevada', en: 'Snowy mountain' },
  { emoji: '🌋', key: 'volcano', pt: 'Vulcão', en: 'Volcano' },
  { emoji: '🪨', key: 'rock_terrain', pt: 'Rocha / terreno', en: 'Rock / terrain' },
  { emoji: '🌾', key: 'open_field', pt: 'Campo aberto', en: 'Open field' },
  { emoji: '🚇', key: 'metro_urban', pt: 'Metro / urbano', en: 'Metro / urban' },
  { emoji: '✈️', key: 'airplane', pt: 'Avião', en: 'Airplane' },
  { emoji: '🛫', key: 'airplane_departure', pt: 'Avião a descolar / aeroporto', en: 'Airplane departure / airport' },
  { emoji: '🛬', key: 'airplane_arrival', pt: 'Avião a aterrar / aeroporto', en: 'Airplane arrival / airport' },
  { emoji: '🛩️', key: 'small_airplane', pt: 'Avião pequeno', en: 'Small airplane' },
  { emoji: '🛄', key: 'baggage_airport', pt: 'Bagagem / aeroporto', en: 'Baggage / airport' },
  { emoji: '🧳', key: 'luggage_travel', pt: 'Mala / viagem', en: 'Luggage / travel' },
  { emoji: '🚂', key: 'train_locomotive', pt: 'Comboio (locomotiva)', en: 'Train (locomotive)' },
  { emoji: '🚆', key: 'train', pt: 'Comboio', en: 'Train' },
  { emoji: '🚄', key: 'high_speed_train', pt: 'Comboio de alta velocidade', en: 'High-speed train' },
  { emoji: '🚅', key: 'bullet_train', pt: 'Comboio bala', en: 'Bullet train' },
  { emoji: '🚉', key: 'train_station', pt: 'Estação de comboio', en: 'Train station' },
  { emoji: '🛳️', key: 'ship_coast', pt: 'Navio / costa', en: 'Ship / coast' },
  { emoji: '⚓', key: 'port_anchor', pt: 'Porto / âncora', en: 'Port / anchor' },
  { emoji: '☀️', key: 'sun_summer', pt: 'Sol / verão', en: 'Sun / summer' },
  { emoji: '🌤️', key: 'sun_clouds', pt: 'Sol com nuvens', en: 'Sun with clouds' },
  { emoji: '🌧️', key: 'rain', pt: 'Chuva', en: 'Rain' },
  { emoji: '❄️', key: 'snow_winter', pt: 'Neve / inverno', en: 'Snow / winter' },
  { emoji: '🌙', key: 'crescent_moon', pt: 'Lua crescente', en: 'Crescent moon' },
  { emoji: '🌕', key: 'full_moon', pt: 'Lua cheia', en: 'Full moon' },
  { emoji: '🌑', key: 'new_moon', pt: 'Lua nova', en: 'New moon' },
  { emoji: '🌛', key: 'first_quarter_moon', pt: 'Lua (quarto crescente)', en: 'First quarter moon' },
  { emoji: '🌜', key: 'last_quarter_moon', pt: 'Lua (quarto minguante)', en: 'Last quarter moon' },
  { emoji: '🌃', key: 'night_stars', pt: 'Noite com estrelas', en: 'Night with stars' },
  { emoji: '🌌', key: 'milky_way', pt: 'Via Láctea / noite', en: 'Milky Way / night sky' },
  { emoji: '🌠', key: 'shooting_star_night', pt: 'Estrela cadente / noite', en: 'Shooting star / night' },
  { emoji: '🌟', key: 'star_bright', pt: 'Estrela brilhante', en: 'Glowing star' },
  { emoji: '⭐', key: 'star', pt: 'Estrela', en: 'Star' },
  { emoji: '✨', key: 'sparkle', pt: 'Brilho', en: 'Sparkle' },
  { emoji: '💫', key: 'shooting_star', pt: 'Estrela cadente', en: 'Shooting star' },
  { emoji: '🔥', key: 'fire_intensity', pt: 'Fogo / intensidade', en: 'Fire / intensity' },
  { emoji: '💨', key: 'speed', pt: 'Velocidade', en: 'Speed' },
  { emoji: '⚡', key: 'energy', pt: 'Energia', en: 'Energy' },
  { emoji: '💪', key: 'strength', pt: 'Força', en: 'Strength' },
  { emoji: '🎯', key: 'goal', pt: 'Objetivo', en: 'Goal' },
  { emoji: '🚀', key: 'rocket_record', pt: 'Foguete / recorde', en: 'Rocket / record' },
  { emoji: '🦅', key: 'eagle', pt: 'Águia', en: 'Eagle' },
  { emoji: '🐢', key: 'turtle_slow_pace', pt: 'Tartaruga / ritmo lento', en: 'Turtle / slow pace' },
  { emoji: '🐇', key: 'rabbit_fast_pace', pt: 'Coelho / ritmo rápido', en: 'Rabbit / fast pace' },
  { emoji: '🦌', key: 'deer', pt: 'Veado', en: 'Deer' },
  { emoji: '🐕', key: 'dog', pt: 'Cão', en: 'Dog' },
  { emoji: '🦁', key: 'lion', pt: 'Leão', en: 'Lion' },
  { emoji: '🦙', key: 'llama', pt: 'Lhama', en: 'Llama' },
  { emoji: '🦏', key: 'rhino', pt: 'Rinoceronte', en: 'Rhinoceros' },
  { emoji: '🐨', key: 'koala', pt: 'Coala', en: 'Koala' },
  { emoji: '🐒', key: 'monkey', pt: 'Macaco', en: 'Monkey' },
  { emoji: '🐷', key: 'pig', pt: 'Porco', en: 'Pig' },
  { emoji: '🐄', key: 'cow', pt: 'Vaca', en: 'Cow' },
  { emoji: '🦆', key: 'duck', pt: 'Pato', en: 'Duck' },
  { emoji: '🐀', key: 'rat', pt: 'Rato', en: 'Rat' },
  { emoji: '🫎', key: 'moose', pt: 'Alce', en: 'Moose' },
  { emoji: '🐟', key: 'fish', pt: 'Peixe', en: 'Fish' },
  { emoji: '🎉', key: 'celebration', pt: 'Celebração', en: 'Celebration' },
  { emoji: '🎊', key: 'confetti', pt: 'Confetti', en: 'Confetti' },
  { emoji: '🎅', key: 'santa_nikolaus', pt: 'Pai Natal / Nikolaus', en: 'Santa / Nikolaus' },
  { emoji: '🤶', key: 'mrs_santa', pt: 'Mãe Natal', en: 'Mrs Claus' },
  { emoji: '🧑‍🎄', key: 'santa_alt', pt: 'Pai Natal (alternativo)', en: 'Santa (alternate)' },
  { emoji: '🎄', key: 'christmas_tree', pt: 'Árvore de Natal', en: 'Christmas tree' },
  { emoji: '🎁', key: 'gift', pt: 'Prenda', en: 'Gift' },
  { emoji: '🕯️', key: 'candle_advent', pt: 'Vela / Advento', en: 'Candle / Advent' },
  { emoji: '⛄', key: 'snowman', pt: 'Boneco de neve', en: 'Snowman' },
  { emoji: '🎂', key: 'birthday', pt: 'Aniversário', en: 'Birthday' },
  { emoji: '🥳', key: 'party', pt: 'Festa', en: 'Party' },
  { emoji: '🎈', key: 'balloons', pt: 'Balões', en: 'Balloons' },
  { emoji: '🎀', key: 'ribbon_gift', pt: 'Laço / oferta', en: 'Ribbon / gift' },
  { emoji: '🎆', key: 'fireworks', pt: 'Fogo de artifício', en: 'Fireworks' },
  { emoji: '🎇', key: 'sparks', pt: 'Faíscas', en: 'Sparks' },
  { emoji: '🥂', key: 'toast', pt: 'Brinde', en: 'Toast' },
  { emoji: '🍾', key: 'champagne', pt: 'Champanhe', en: 'Champagne' },
  { emoji: '🎃', key: 'halloween', pt: 'Halloween', en: 'Halloween' },
  { emoji: '🪅', key: 'pinata', pt: 'Pinhata', en: 'Piñata' },
  { emoji: '🎭', key: 'carnival_mask', pt: 'Carnaval / máscara', en: 'Carnival / mask' },
  { emoji: '🪩', key: 'disco_party', pt: 'Disco / festa', en: 'Disco / party' },
  { emoji: '🍀', key: 'clover_luck', pt: 'Trevo / sorte', en: 'Clover / luck' },
  { emoji: '❤️', key: 'heart_red', pt: 'Coração vermelho', en: 'Red heart' },
  { emoji: '💙', key: 'heart_blue', pt: 'Coração azul', en: 'Blue heart' },
  { emoji: '💚', key: 'heart_green', pt: 'Coração verde', en: 'Green heart' },
  { emoji: '🧡', key: 'heart_orange', pt: 'Coração laranja', en: 'Orange heart' },
  { emoji: '💜', key: 'heart_purple', pt: 'Coração roxo', en: 'Purple heart' },
  { emoji: '🖤', key: 'heart_black', pt: 'Coração preto', en: 'Black heart' },
  { emoji: '🤍', key: 'heart_white', pt: 'Coração branco', en: 'White heart' },
  { emoji: '🇦🇱', key: 'country_al', pt: 'Albânia', en: 'Albania' },
  { emoji: '🇦🇩', key: 'country_ad', pt: 'Andorra', en: 'Andorra' },
  { emoji: '🇦🇲', key: 'country_am', pt: 'Arménia', en: 'Armenia' },
  { emoji: '🇦🇹', key: 'country_at', pt: 'Áustria', en: 'Austria' },
  { emoji: '🇦🇿', key: 'country_az', pt: 'Azerbaijão', en: 'Azerbaijan' },
  { emoji: '🇧🇾', key: 'country_by', pt: 'Bielorrússia', en: 'Belarus' },
  { emoji: '🇧🇪', key: 'country_be', pt: 'Bélgica', en: 'Belgium' },
  { emoji: '🇧🇦', key: 'country_ba', pt: 'Bósnia e Herzegovina', en: 'Bosnia and Herzegovina' },
  { emoji: '🇧🇬', key: 'country_bg', pt: 'Bulgária', en: 'Bulgaria' },
  { emoji: '🇭🇷', key: 'country_hr', pt: 'Croácia', en: 'Croatia' },
  { emoji: '🇨🇾', key: 'country_cy', pt: 'Chipre', en: 'Cyprus' },
  { emoji: '🇨🇿', key: 'country_cz', pt: 'Chéquia', en: 'Czechia' },
  { emoji: '🇩🇰', key: 'country_dk', pt: 'Dinamarca', en: 'Denmark' },
  { emoji: '🇪🇬', key: 'country_eg', pt: 'Egito', en: 'Egypt' },
  { emoji: '🇪🇪', key: 'country_ee', pt: 'Estónia', en: 'Estonia' },
  { emoji: '🇫🇮', key: 'country_fi', pt: 'Finlândia', en: 'Finland' },
  { emoji: '🇫🇷', key: 'country_fr', pt: 'França', en: 'France' },
  { emoji: '🇬🇪', key: 'country_ge', pt: 'Geórgia', en: 'Georgia' },
  { emoji: '🇩🇪', key: 'country_de', pt: 'Alemanha', en: 'Germany' },
  { emoji: '🇬🇷', key: 'country_gr', pt: 'Grécia', en: 'Greece' },
  { emoji: '🇭🇺', key: 'country_hu', pt: 'Hungria', en: 'Hungary' },
  { emoji: '🇮🇸', key: 'country_is', pt: 'Islândia', en: 'Iceland' },
  { emoji: '🇮🇪', key: 'country_ie', pt: 'Irlanda', en: 'Ireland' },
  { emoji: '🇮🇹', key: 'country_it', pt: 'Itália', en: 'Italy' },
  { emoji: '🇱🇻', key: 'country_lv', pt: 'Letónia', en: 'Latvia' },
  { emoji: '🇱🇹', key: 'country_lt', pt: 'Lituânia', en: 'Lithuania' },
  { emoji: '🇱🇺', key: 'country_lu', pt: 'Luxemburgo', en: 'Luxembourg' },
  { emoji: '🇲🇦', key: 'country_ma', pt: 'Marrocos', en: 'Morocco' },
  { emoji: '🇲🇩', key: 'country_md', pt: 'Moldávia', en: 'Moldova' },
  { emoji: '🇲🇨', key: 'country_mc', pt: 'Mónaco', en: 'Monaco' },
  { emoji: '🇳🇱', key: 'country_nl', pt: 'Países Baixos', en: 'Netherlands' },
  { emoji: '🇳🇴', key: 'country_no', pt: 'Noruega', en: 'Norway' },
  { emoji: '🇵🇱', key: 'country_pl', pt: 'Polónia', en: 'Poland' },
  { emoji: '🇵🇹', key: 'country_pt', pt: 'Portugal', en: 'Portugal' },
  { emoji: '🇷🇴', key: 'country_ro', pt: 'Roménia', en: 'Romania' },
  { emoji: '🇷🇺', key: 'country_ru', pt: 'Rússia', en: 'Russia' },
  { emoji: '🇷🇸', key: 'country_rs', pt: 'Sérvia', en: 'Serbia' },
  { emoji: '🇸🇰', key: 'country_sk', pt: 'Eslováquia', en: 'Slovakia' },
  { emoji: '🇸🇮', key: 'country_si', pt: 'Eslovénia', en: 'Slovenia' },
  { emoji: '🇪🇸', key: 'country_es', pt: 'Espanha', en: 'Spain' },
  { emoji: '🇸🇪', key: 'country_se', pt: 'Suécia', en: 'Sweden' },
  { emoji: '🇨🇭', key: 'country_ch', pt: 'Suíça', en: 'Switzerland' },
  { emoji: '🇹🇷', key: 'country_tr', pt: 'Turquia', en: 'Turkey' },
  { emoji: '🇺🇦', key: 'country_ua', pt: 'Ucrânia', en: 'Ukraine' },
  { emoji: '🇬🇧', key: 'country_gb', pt: 'Reino Unido', en: 'United Kingdom' },
  { emoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', key: 'country_scotland', pt: 'Escócia', en: 'Scotland' },
  { emoji: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', key: 'country_wales', pt: 'País de Gales', en: 'Wales' },
  { emoji: '🏴󠁧󠁢󠁮󠁩󠁲󠁿', key: 'country_northern_ireland', pt: 'Irlanda do Norte', en: 'Northern Ireland' },
]

export const EMOJI_OPTIONS: EmojiOption[] = EMOJI_DEFINITIONS.map(({ emoji, key }) => ({
  emoji,
  labelKey: key,
}))

export function buildEmojiLocaleResources(): {
  pt: Record<string, string>
  en: Record<string, string>
} {
  const pt: Record<string, string> = {}
  const en: Record<string, string> = {}

  for (const { key, pt: ptLabel, en: enLabel } of EMOJI_DEFINITIONS) {
    pt[key] = ptLabel
    en[key] = enLabel
  }

  return { pt, en }
}
