#!/usr/bin/env npx tsx
/**
 * Generate in-app privacy policy content from scripts/privacy-policy.template.md.
 *
 * Usage: npm run generate:privacy
 * Output: src/generated/privacyPolicy.content.ts, .env.privacy.generated
 */
import { mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import {
  loadEnvFile,
  loadPrivacyPolicyTemplate,
  missingPrivacyEnvKeys,
  parseLocaleSections,
  resolvePrivacyPolicyValues,
  resolvePrivacyPolicyValuesForLocale,
  substitutePlaceholders,
} from './privacyPolicy.js'

const ROOT = resolve(import.meta.dirname, '..')
const GENERATED_DIR = resolve(ROOT, 'src/generated')
const CONTENT_FILE = resolve(GENERATED_DIR, 'privacyPolicy.content.ts')
const PRIVACY_ENV_FILE = resolve(ROOT, '.env.privacy.generated')

loadEnvFile(resolve(ROOT, '.env.local'))
loadEnvFile(resolve(ROOT, '.env'))

const required = process.env.PRIVACY_REQUIRED === 'true'
const values = resolvePrivacyPolicyValues()

if (!values) {
  const missing = missingPrivacyEnvKeys()
  if (required) {
    console.error(
      `Privacy policy generation failed. Missing: ${missing.join(', ')}. Set PRIVACY_* in .env.local or CI.`,
    )
    process.exit(1)
  }

  try {
    rmSync(CONTENT_FILE, { force: true })
    rmSync(PRIVACY_ENV_FILE, { force: true })
  } catch {
    // ignore
  }

  console.log(`Skipping privacy policy generation (missing: ${missing.join(', ')}).`)
  process.exit(0)
}

const template = loadPrivacyPolicyTemplate(ROOT)
const sections = parseLocaleSections(template)

const ptSection = sections.get('pt')
const enSection = sections.get('en')
const esSection = sections.get('es')
const deSection = sections.get('de')
if (!ptSection || !enSection || !esSection || !deSection) {
  console.error('Missing pt, en, es, or de section in privacy-policy.template.md')
  process.exit(1)
}

const ptMarkdown = substitutePlaceholders(
  ptSection,
  resolvePrivacyPolicyValuesForLocale(values, 'pt'),
)
const enMarkdown = substitutePlaceholders(
  enSection,
  resolvePrivacyPolicyValuesForLocale(values, 'en'),
)
const esMarkdown = substitutePlaceholders(
  esSection,
  resolvePrivacyPolicyValuesForLocale(values, 'es'),
)
const deMarkdown = substitutePlaceholders(
  deSection,
  resolvePrivacyPolicyValuesForLocale(values, 'de'),
)

mkdirSync(GENERATED_DIR, { recursive: true })

writeFileSync(
  CONTENT_FILE,
  `// Generated by scripts/generate-privacy-policy.ts — do not commit
export const privacyPolicyContent = {
  enabled: true,
  effectiveDate: ${JSON.stringify(values.EFFECTIVE_DATE)},
  instanceName: ${JSON.stringify(values.INSTANCE_NAME)},
  pt: ${JSON.stringify(ptMarkdown)},
  en: ${JSON.stringify(enMarkdown)},
  es: ${JSON.stringify(esMarkdown)},
  de: ${JSON.stringify(deMarkdown)},
} as const
`,
  'utf8',
)

writeFileSync(
  PRIVACY_ENV_FILE,
  [
    '# Generated by npm run generate:privacy — do not commit',
    'VITE_PRIVACY_POLICY_ENABLED=true',
    '',
  ].join('\n'),
  'utf8',
)

console.log(`Privacy policy content generated (${values.EFFECTIVE_DATE})`)
